// Additional Advanced and Expert grammar banks.
//
// The original six Advanced and four Expert topics (grammar-client.js) total
// only 80 questions — under two full lessons once a lesson means 50 exercises.
// These banks bring each tier up to a size that supports real categories.
// Same shape as grammar-client.js: { q, options[4], correct, explain }.
//
// Kept in a separate file purely for size: grammar-client.js is already large,
// and lesson-structure.js merges the two into one bank per tier.

export const ADVANCED_EXTRA = [
  {
    id: "reported-speech",
    label: "Reported Speech",
    emoji: "💬",
    questions: [
      { q: 'He said, "I am tired." → He said he ____ tired.', options: ["is", "was", "were", "has been"], correct: 1,
        explain: "Reporting a past statement shifts present to past: am → was." },
      { q: 'She said, "I will call you." → She said she ____ call me.', options: ["will", "would", "shall", "won't"], correct: 1,
        explain: "will → would when the reporting verb is in the past." },
      { q: 'They asked, "Where do you live?" → They asked where I ____.', options: ["do live", "lived", "did live", "live"], correct: 1,
        explain: "Reported questions use statement word order and shift the tense back." },
      { q: 'He told ____ that the shop was closed.', options: ["to me", "me", "at me", "for me"], correct: 1,
        explain: '"Tell" takes a direct object with no preposition: tell me. "Say" would need "to me".' },
      { q: 'She said, "I saw him yesterday." → She said she had seen him ____.', options: ["yesterday", "the day before", "tomorrow", "last day"], correct: 1,
        explain: "Time words shift too: yesterday → the day before." },
      { q: 'He asked me ____ I wanted coffee.', options: ["that", "if", "what", "which"], correct: 1,
        explain: "Yes/no questions are reported with if or whether." },
      { q: 'Mum said, "Don\'t be late." → Mum told me ____ late.', options: ["don't be", "not to be", "to not being", "no be"], correct: 1,
        explain: "Negative commands are reported with: told + object + not to + verb." },
      { q: '"I have finished," he said. → He said he ____ finished.', options: ["has", "had", "have", "was"], correct: 1,
        explain: "Present perfect shifts back to past perfect in reported speech." },
    ],
  },
  {
    id: "passive-voice",
    label: "Passive Voice",
    emoji: "🔄",
    questions: [
      { q: "The letter ____ yesterday.", options: ["sent", "was sent", "is sent", "has sent"], correct: 1,
        explain: "Past simple passive = was/were + past participle." },
      { q: "This bridge ____ in 1890.", options: ["built", "was built", "is building", "has built"], correct: 1,
        explain: "The bridge did not build itself — the doer is unknown or unimportant, so passive." },
      { q: "The room ____ every morning.", options: ["cleans", "is cleaned", "is cleaning", "cleaned"], correct: 1,
        explain: "A repeated action done to the subject: present simple passive." },
      { q: "The problem ____ solved by the new team.", options: ["is being", "is been", "being", "be"], correct: 0,
        explain: "Present continuous passive = is/are being + past participle." },
      { q: "My bike ____ last week!", options: ["stole", "was stolen", "has stole", "is stealing"], correct: 1,
        explain: "The bike received the action — past passive with the participle stolen." },
      { q: "English ____ all over the world.", options: ["speaks", "is spoken", "is speaking", "spoken"], correct: 1,
        explain: "People speak it; the language is spoken. The subject receives the action." },
      { q: "The report must ____ by Friday.", options: ["finish", "be finished", "finished", "being finished"], correct: 1,
        explain: "After a modal, the passive is: modal + be + past participle." },
      { q: "The cake ____ by my grandmother.", options: ["made", "was made", "did make", "is make"], correct: 1,
        explain: 'Use "by" to name the doer in a passive sentence: was made by her.' },
    ],
  },
  {
    id: "relative-clauses",
    label: "Relative Clauses",
    emoji: "🔗",
    questions: [
      { q: "The man ____ lives next door is a doctor.", options: ["which", "who", "whose", "whom"], correct: 1,
        explain: "Who refers to people; which refers to things." },
      { q: "The book ____ I bought is excellent.", options: ["who", "whose", "which", "where"], correct: 2,
        explain: "Which (or that) refers to things." },
      { q: "That's the girl ____ brother plays in my team.", options: ["who", "which", "whose", "who's"], correct: 2,
        explain: "Whose shows possession: her brother → whose brother." },
      { q: "This is the café ____ we first met.", options: ["which", "that", "where", "who"], correct: 2,
        explain: "Where refers to a place inside a relative clause." },
      { q: "My sister, ____ lives in Cluj, is a vet.", options: ["that", "who", "which", "whom"], correct: 1,
        explain: 'After a comma (non-defining clause) you cannot use "that" — use who for people.' },
      { q: "The year ____ we moved was 2019.", options: ["which", "when", "where", "who"], correct: 1,
        explain: "When refers to a time." },
      { q: "The film ____ we watched was boring.", options: ["who", "whose", "that", "where"], correct: 2,
        explain: "That works for things in a defining clause." },
      { q: "The people ____ I work are very kind.", options: ["who", "with whom", "which", "whose"], correct: 1,
        explain: 'The verb needs "with": with whom I work (formal) or who I work with.' },
    ],
  },
  {
    id: "modals-deduction",
    label: "Modals of Deduction",
    emoji: "🕵️",
    questions: [
      { q: "The lights are on — someone ____ be home.", options: ["must", "can't", "might not", "shouldn't"], correct: 0,
        explain: "Must = you are almost certain something is true." },
      { q: "He ____ be at school — it's Sunday!", options: ["must", "can't", "should", "may"], correct: 1,
        explain: "Can't = you are almost certain something is NOT true." },
      { q: "She ____ be tired; she slept only four hours.", options: ["can't", "must", "mustn't", "couldn't"], correct: 1,
        explain: "The evidence points strongly to it being true → must." },
      { q: "It ____ rain later — the sky is grey.", options: ["must", "can't", "might", "mustn't"], correct: 2,
        explain: "Might = it is possible but not certain." },
      { q: "That ____ be Ana — she's in Spain this week.", options: ["must", "can't", "may", "should"], correct: 1,
        explain: "A logical impossibility takes can't, never mustn't." },
      { q: "They ____ have left already; their car is gone.", options: ["must", "can't", "shouldn't", "didn't"], correct: 0,
        explain: "Deduction about the past: must + have + past participle." },
      { q: "He ____ have seen us — he was looking the other way.", options: ["must", "can't", "should", "would"], correct: 1,
        explain: "Certainty that something did NOT happen: can't have + past participle." },
      { q: "She ____ be about thirty, I'd guess.", options: ["must", "can't", "might", "mustn't"], correct: 2,
        explain: '"I\'d guess" signals uncertainty → might.' },
    ],
  },
  {
    id: "gerunds-infinitives",
    label: "Gerunds & Infinitives",
    emoji: "🎯",
    questions: [
      { q: "I enjoy ____ football.", options: ["to play", "playing", "play", "played"], correct: 1,
        explain: "Enjoy is always followed by the -ing form." },
      { q: "She decided ____ early.", options: ["leaving", "to leave", "leave", "left"], correct: 1,
        explain: "Decide takes the to-infinitive." },
      { q: "He avoided ____ to her.", options: ["to talk", "talking", "talk", "talked"], correct: 1,
        explain: "Avoid, mind, and finish all take -ing." },
      { q: "I'm looking forward to ____ you.", options: ["see", "seeing", "saw", "have seen"], correct: 1,
        explain: 'Here "to" is a preposition, not an infinitive marker — so -ing follows.' },
      { q: "We hope ____ you soon.", options: ["seeing", "to see", "see", "saw"], correct: 1,
        explain: "Hope, want, and plan take the to-infinitive." },
      { q: "Do you mind ____ the window?", options: ["to open", "opening", "open", "opened"], correct: 1,
        explain: "Mind is followed by -ing." },
      { q: "He stopped ____ because it was bad for him.", options: ["to smoke", "smoking", "smoke", "smoked"], correct: 1,
        explain: "Stop + -ing = quit the activity. Stop + to = pause in order to do something." },
      { q: "It's no use ____ about it now.", options: ["to worry", "worrying", "worry", "worried"], correct: 1,
        explain: 'The fixed pattern is "it\'s no use" + -ing.' },
    ],
  },
  {
    id: "articles",
    label: "Articles",
    emoji: "📌",
    questions: [
      { q: "I saw ____ elephant at the zoo.", options: ["a", "an", "the", "—"], correct: 1,
        explain: "An goes before a vowel SOUND: an elephant." },
      { q: "She is ____ best student in the class.", options: ["a", "an", "the", "—"], correct: 2,
        explain: "Superlatives take the: the best." },
      { q: "He plays ____ guitar beautifully.", options: ["a", "an", "the", "—"], correct: 2,
        explain: "Musical instruments take the: play the guitar." },
      { q: "____ water boils at 100 degrees.", options: ["A", "An", "The", "—"], correct: 3,
        explain: "General truths about uncountable nouns take no article." },
      { q: "We went to ____ university in Cluj.", options: ["a", "an", "the", "—"], correct: 0,
        explain: '"University" starts with a "yoo" sound, so it takes a, not an.' },
      { q: "I go to ____ school by bus.", options: ["a", "an", "the", "—"], correct: 3,
        explain: "For the purpose of the institution (studying) there is no article: go to school." },
      { q: "Have you seen ____ film I recommended?", options: ["a", "an", "the", "—"], correct: 2,
        explain: "A specific one that both speakers know about → the." },
      { q: "She wants to be ____ engineer.", options: ["a", "an", "the", "—"], correct: 1,
        explain: 'Jobs take a/an, and "engineer" begins with a vowel sound → an.' },
    ],
  },
  {
    id: "quantifiers",
    label: "Quantifiers",
    emoji: "⚖️",
    questions: [
      { q: "There isn't ____ milk left.", options: ["many", "much", "few", "a lot"], correct: 1,
        explain: "Much goes with uncountable nouns; many goes with countable ones." },
      { q: "How ____ apples do you want?", options: ["much", "many", "little", "a lot"], correct: 1,
        explain: "Apples are countable → many." },
      { q: "I have ____ friends here — only two.", options: ["a few", "few", "little", "a little"], correct: 1,
        explain: 'Few = not many (negative). "A few" would mean some, which is positive.' },
      { q: "Add ____ salt, just a pinch.", options: ["a few", "few", "a little", "many"], correct: 2,
        explain: "A little = a small amount of something uncountable." },
      { q: "____ of the students passed the exam.", options: ["Most", "Most of", "The most", "Almost"], correct: 0,
        explain: 'Before "of the" you use Most: Most of the students.' },
      { q: "There were ____ people at the concert.", options: ["much", "a lot of", "a little", "less"], correct: 1,
        explain: "A lot of works with both countable and uncountable nouns." },
      { q: "I have ____ time, so let's hurry.", options: ["a little", "little", "few", "a few"], correct: 1,
        explain: "Little = almost none, which is why we must hurry." },
      { q: "____ of my two brothers lives abroad.", options: ["Both", "Neither", "All", "None"], correct: 1,
        explain: "Neither = not one and not the other, used for exactly two." },
    ],
  },
  {
    id: "adverb-order",
    label: "Word Order & Adverbs",
    emoji: "🔤",
    questions: [
      { q: "She ____ late for school.", options: ["is never", "never is", "is not never", "never"], correct: 0,
        explain: "Adverbs of frequency go AFTER the verb to be." },
      { q: "He ____ to the gym on Mondays.", options: ["goes usually", "usually goes", "goes usual", "usual goes"], correct: 1,
        explain: "With other verbs, the frequency adverb goes BEFORE the verb." },
      { q: "I saw a ____ car.", options: ["red big Italian", "big red Italian", "Italian big red", "big Italian red"], correct: 1,
        explain: "Adjective order: size → colour → origin." },
      { q: "They played ____ yesterday.", options: ["well very", "very well", "good very", "very good"], correct: 1,
        explain: "The adverb well describes how they played; very intensifies it." },
      { q: "She speaks English ____.", options: ["fluent", "fluently", "fluent-ly", "with fluent"], correct: 1,
        explain: "Modifying a verb needs an adverb: fluently." },
      { q: "____ I finished the book.", options: ["Yesterday night", "Last night", "The last night", "In last night"], correct: 1,
        explain: 'The fixed phrase is "last night" — never "yesterday night".' },
      { q: "He drives ____ carefully.", options: ["enough", "too much", "very", "so much"], correct: 2,
        explain: "Very intensifies the adverb carefully directly." },
      { q: "We ____ go to the seaside in summer.", options: ["go often", "often go", "often going", "go oftenly"], correct: 1,
        explain: "Often sits before the main verb." },
    ],
  },
  {
    id: "used-to-would",
    label: "Used to & Would",
    emoji: "⏮️",
    questions: [
      { q: "I ____ play outside all day when I was a kid.", options: ["use to", "used to", "am used to", "would used"], correct: 1,
        explain: "Used to describes a past habit that has stopped." },
      { q: "Did you ____ live in Brașov?", options: ["used to", "use to", "using to", "be used to"], correct: 1,
        explain: 'After "did", the base form is used: did you use to.' },
      { q: "I'm ____ getting up early now.", options: ["used to", "use to", "used", "using to"], correct: 0,
        explain: '"Be used to" + -ing = something is now familiar. Different from "used to".' },
      { q: "Every summer we ____ visit our grandparents.", options: ["would", "will", "used", "use"], correct: 0,
        explain: "Would describes repeated past actions in storytelling." },
      { q: "She ____ have long hair, but she cut it.", options: ["use to", "used to", "would", "is used to"], correct: 1,
        explain: 'Would does not work with states like "have long hair" — use "used to".' },
      { q: "He isn't ____ to the cold weather here.", options: ["use", "used", "using", "uses"], correct: 1,
        explain: "The adjective phrase is be used to." },
      { q: "I didn't ____ like olives, but now I do.", options: ["used to", "use to", "used", "using"], correct: 1,
        explain: 'After "didn\'t" the base form appears: use to.' },
      { q: "You'll soon ____ used to the new school.", options: ["get", "make", "have", "be got"], correct: 0,
        explain: "Get used to = the process of becoming familiar with something." },
    ],
  },
  {
    id: "question-tags",
    label: "Question Tags",
    emoji: "❓",
    questions: [
      { q: "You're coming, ____?", options: ["are you", "aren't you", "don't you", "isn't it"], correct: 1,
        explain: "A positive sentence takes a negative tag." },
      { q: "She doesn't like coffee, ____?", options: ["does she", "doesn't she", "is she", "did she"], correct: 0,
        explain: "A negative sentence takes a positive tag." },
      { q: "They went home, ____?", options: ["don't they", "didn't they", "weren't they", "haven't they"], correct: 1,
        explain: "Past simple went → the tag uses did." },
      { q: "It's cold today, ____?", options: ["is it", "isn't it", "doesn't it", "aren't it"], correct: 1,
        explain: 'The verb is "is", so the tag is isn\'t it.' },
      { q: "Let's go, ____?", options: ["will we", "shall we", "don't we", "aren't we"], correct: 1,
        explain: '"Let\'s" always takes the tag shall we.' },
      { q: "You can swim, ____?", options: ["can't you", "can you", "don't you", "aren't you"], correct: 0,
        explain: "The modal can is repeated in the negative tag." },
      { q: "Nobody called, ____?", options: ["did they", "didn't they", "did he", "didn't he"], correct: 0,
        explain: 'Nobody counts as negative, so the tag is positive, and "they" refers back to nobody.' },
      { q: "Open the window, ____?", options: ["do you", "will you", "aren't you", "shall you"], correct: 1,
        explain: "Imperatives take the tag will you." },
    ],
  },
  {
    id: "so-such-enough",
    label: "So, Such, Too, Enough",
    emoji: "📏",
    questions: [
      { q: "It was ____ a good film!", options: ["so", "such", "too", "very much"], correct: 1,
        explain: "Such goes before a noun phrase: such a good film." },
      { q: "The tea is ____ hot to drink.", options: ["so", "such", "too", "enough"], correct: 2,
        explain: "Too + adjective + to = more than is acceptable." },
      { q: "She isn't old ____ to drive.", options: ["so", "such", "too", "enough"], correct: 3,
        explain: "Enough comes AFTER the adjective: old enough." },
      { q: "He was ____ tired that he fell asleep.", options: ["such", "so", "too", "enough"], correct: 1,
        explain: "So + adjective + that expresses a result." },
      { q: "We have ____ money to buy it.", options: ["enough", "too", "such", "so"], correct: 0,
        explain: "Enough comes BEFORE a noun: enough money." },
      { q: "There were ____ many people we couldn't get in.", options: ["such", "so", "too", "very"], correct: 1,
        explain: "So goes with many/much: so many people that..." },
      { q: "It's ____ an expensive car for us.", options: ["so", "too", "such", "enough"], correct: 2,
        explain: "Before a noun phrase you need such, not so." },
      { q: "The box was ____ heavy for me to lift.", options: ["so", "such", "too", "enough"], correct: 2,
        explain: 'Too + adjective + for + person + to = it exceeded what I could do.' },
    ],
  },
  {
    id: "linking-contrast",
    label: "Linking & Contrast",
    emoji: "🪢",
    questions: [
      { q: "____ the rain, we went out.", options: ["Although", "Despite", "However", "But"], correct: 1,
        explain: "Despite is followed by a noun; although needs a full clause." },
      { q: "____ it was raining, we went out.", options: ["Despite", "In spite of", "Although", "However"], correct: 2,
        explain: "Although introduces a clause with a subject and verb." },
      { q: "It was cold; ____, we enjoyed the walk.", options: ["although", "despite", "however", "whereas"], correct: 2,
        explain: "However links two sentences and is followed by a comma." },
      { q: "He studied hard ____ pass the exam.", options: ["for", "so that", "in order to", "because"], correct: 2,
        explain: "In order to + base verb expresses purpose." },
      { q: "She left early ____ she wouldn't miss the train.", options: ["in order to", "so that", "despite", "because of"], correct: 1,
        explain: "So that introduces a clause with its own subject and verb." },
      { q: "We stayed in ____ the bad weather.", options: ["although", "because", "because of", "so"], correct: 2,
        explain: "Because of is followed by a noun phrase." },
      { q: "I like tea, ____ my brother prefers coffee.", options: ["whereas", "despite", "however", "although of"], correct: 0,
        explain: "Whereas directly contrasts two facts." },
      { q: "____ working all night, he didn't finish.", options: ["Although", "Despite", "However", "Whereas"], correct: 1,
        explain: "Before an -ing form you need Despite, not Although." },
    ],
  },
  {
    id: "prepositions-advanced",
    label: "Tricky Prepositions",
    emoji: "🧭",
    questions: [
      { q: "She's good ____ maths.", options: ["in", "at", "on", "with"], correct: 1,
        explain: "The fixed pattern is good at something." },
      { q: "I'm interested ____ history.", options: ["for", "about", "in", "on"], correct: 2,
        explain: "Interested in is fixed." },
      { q: "He depends ____ his parents.", options: ["of", "from", "on", "to"], correct: 2,
        explain: "Depend on — never depend of, which is a common Romanian-speaker slip." },
      { q: "It depends ____ the weather.", options: ["of", "on", "by", "from"], correct: 1,
        explain: 'Same rule: "depinde de" translates to depends ON.' },
      { q: "Congratulations ____ your exam!", options: ["for", "with", "on", "about"], correct: 2,
        explain: "Congratulations on something is the fixed form." },
      { q: "She's married ____ a doctor.", options: ["with", "to", "by", "at"], correct: 1,
        explain: 'Married TO someone — "married with" is a direct translation error.' },
      { q: "I apologised ____ being late.", options: ["of", "for", "about", "to"], correct: 1,
        explain: "Apologise for + the thing; apologise to + the person." },
      { q: "We arrived ____ the airport at six.", options: ["to", "in", "at", "on"], correct: 2,
        explain: "Arrive AT a place; arrive IN a city or country." },
    ],
  },
];

export const EXPERT_EXTRA = [
  {
    id: "collocations",
    label: "Collocations",
    emoji: "🧲",
    questions: [
      { q: "I need to ____ a decision quickly.", options: ["do", "make", "take", "get"], correct: 1,
        explain: "Make a decision is the standard collocation." },
      { q: "Could you ____ me a favour?", options: ["make", "do", "give", "take"], correct: 1,
        explain: "Do a favour, but make a mistake — the pairings are fixed." },
      { q: "She ____ a great effort to finish on time.", options: ["did", "made", "took", "gave"], correct: 1,
        explain: "Make an effort is fixed." },
      { q: "They ____ business with us for years.", options: ["made", "have done", "took", "gave"], correct: 1,
        explain: "Do business is the standard pairing." },
      { q: "He ____ a risk by investing everything.", options: ["did", "made", "took", "had"], correct: 2,
        explain: "Take a risk is the collocation." },
      { q: "Let me ____ a quick look.", options: ["do", "make", "take", "give"], correct: 2,
        explain: "Take a look (or have a look) — never make a look." },
      { q: "The company ____ a huge profit last year.", options: ["did", "made", "took", "won"], correct: 1,
        explain: "Make a profit is fixed; win a profit is not English." },
      { q: "She ____ me a compliment on my work.", options: ["did", "made", "paid", "took"], correct: 2,
        explain: "Pay someone a compliment is the idiomatic pairing." },
    ],
  },
  {
    id: "false-friends-ro",
    label: "False Friends (RO→EN)",
    emoji: "🪞",
    questions: [
      { q: 'Romanian "actual" (current) in English is:', options: ["actual", "current", "actually", "factual"], correct: 1,
        explain: 'English "actual" means real/true, not present-day. "Actual" în română = current.' },
      { q: 'Romanian "eventual" (possibly) in English is:', options: ["eventual", "eventually", "possible", "finally"], correct: 2,
        explain: 'English "eventual" means happening at the end, not "maybe".' },
      { q: 'Romanian "sensibil" (sensitive) in English is:', options: ["sensible", "sensitive", "sensual", "senseful"], correct: 1,
        explain: '"Sensible" means having good judgement — a different word entirely.' },
      { q: 'Romanian "a realiza" (to notice) in English is:', options: ["to realise", "to realize a project", "to achieve", "to make"], correct: 0,
        explain: "Realise = to become aware. For projects, English uses carry out or complete." },
      { q: 'Romanian "librărie" in English is:', options: ["library", "bookshop", "librarian", "booking"], correct: 1,
        explain: "Library = bibliotecă. Librărie = bookshop." },
      { q: 'Romanian "a controla" (to check) in English is:', options: ["to control", "to check", "to controll", "to command"], correct: 1,
        explain: "Control means to have power over; checking a document is to check it." },
      { q: 'Romanian "fabrică" in English is:', options: ["fabric", "factory", "fabrication", "manufacture"], correct: 1,
        explain: "Fabric = material (textile). Fabrică = factory." },
      { q: 'Romanian "a asista la" (to attend) in English is:', options: ["to assist", "to attend", "to assist at", "to help"], correct: 1,
        explain: "Assist = to help. Being present at an event is to attend it." },
    ],
  },
  {
    id: "register",
    label: "Formal & Informal",
    emoji: "🎩",
    questions: [
      { q: "Most formal way to ask: ", options: ["Gimme that file.", "Can I have the file?", "Could you send me the file?", "I would be grateful if you could send me the file."], correct: 3,
        explain: "Longer, more indirect structures signal greater formality." },
      { q: "In a business email, replace \"I want to\" with:", options: ["I wanna", "I would like to", "I gonna", "I need"], correct: 1,
        explain: "Would like to is the polite, neutral register." },
      { q: "Formal alternative to \"find out\":", options: ["figure out", "ascertain", "check out", "suss out"], correct: 1,
        explain: "Phrasal verbs are informal; single Latinate verbs are formal." },
      { q: "Formal alternative to \"put off\":", options: ["postpone", "call off", "delay it a bit", "push back"], correct: 0,
        explain: "Postpone is the formal single-word equivalent." },
      { q: "Which closing suits a formal letter to an unknown person?", options: ["Cheers", "Yours faithfully", "See ya", "Best"], correct: 1,
        explain: 'Yours faithfully pairs with "Dear Sir/Madam"; Yours sincerely with a named person.' },
      { q: "Informal equivalent of \"require assistance\":", options: ["need help", "necessitate aid", "request support", "demand help"], correct: 0,
        explain: "Everyday speech prefers short Germanic words: need help." },
      { q: "Most appropriate in a job application:", options: ["I reckon I'd be great.", "I believe I would be well suited to this role.", "I'd be awesome at this.", "I think I'm the best."], correct: 1,
        explain: "Measured, hedged phrasing is expected in formal applications." },
      { q: "Formal alternative to \"get in touch with\":", options: ["reach out to", "contact", "hit up", "ping"], correct: 1,
        explain: "Contact is the neutral formal verb." },
    ],
  },
  {
    id: "inversion",
    label: "Inversion & Emphasis",
    emoji: "🔀",
    questions: [
      { q: "Never ____ such a beautiful sunset.", options: ["I have seen", "have I seen", "I saw", "did I saw"], correct: 1,
        explain: "A negative adverb at the start forces subject-verb inversion." },
      { q: "Not only ____ late, but he also forgot the tickets.", options: ["he was", "was he", "he is", "he had"], correct: 1,
        explain: "Not only at the front triggers inversion: was he." },
      { q: "Rarely ____ so hard.", options: ["I work", "do I work", "I do work", "work I"], correct: 1,
        explain: "Rarely, seldom, and hardly all trigger inversion with the auxiliary." },
      { q: "____ had I arrived when the phone rang.", options: ["No sooner", "Hardly than", "Scarcely when", "As soon"], correct: 0,
        explain: "No sooner... than is the fixed pair; hardly pairs with when." },
      { q: "Only after the meeting ____ the truth.", options: ["I learned", "did I learn", "I did learn", "learned I"], correct: 1,
        explain: '"Only after..." at the front requires the inverted auxiliary.' },
      { q: "It ____ my sister who called, not my mother.", options: ["is", "was", "were", "has been"], correct: 1,
        explain: "Cleft sentences with It was... who put emphasis on the subject." },
      { q: "____ I known, I would have helped.", options: ["If", "Had", "Have", "Would"], correct: 1,
        explain: 'Had I known = a formal inversion replacing "If I had known".' },
      { q: "Little ____ that he was already gone.", options: ["she knew", "did she know", "knew she", "she did know"], correct: 1,
        explain: '"Little" used negatively at the front triggers inversion.' },
    ],
  },
  {
    id: "unreal-past",
    label: "Unreal Past & Wishes",
    emoji: "🌙",
    questions: [
      { q: "I wish I ____ taller.", options: ["am", "was", "were", "will be"], correct: 2,
        explain: "Were is the standard subjunctive form after wish for all persons." },
      { q: "If only I ____ studied harder!", options: ["have", "had", "would", "did"], correct: 1,
        explain: "Regret about the past takes if only + past perfect." },
      { q: "I'd rather you ____ smoke here.", options: ["don't", "didn't", "won't", "not"], correct: 1,
        explain: "I'd rather + someone + past simple expresses a present preference." },
      { q: "It's time we ____ home.", options: ["go", "went", "will go", "have gone"], correct: 1,
        explain: "It's time + past simple refers to the present — an unreal past form." },
      { q: "He talks as if he ____ everything.", options: ["knows", "knew", "has known", "will know"], correct: 1,
        explain: "As if + past simple signals that the situation is not true." },
      { q: "I wish you ____ stop interrupting.", options: ["will", "would", "did", "have"], correct: 1,
        explain: "Wish + would expresses annoyance at someone else's habit." },
      { q: "Suppose you ____ the lottery — what then?", options: ["win", "won", "have won", "will win"], correct: 1,
        explain: "Suppose + past simple imagines an unreal present situation." },
      { q: "If I ____ you, I'd apologise.", options: ["am", "was", "were", "would be"], correct: 2,
        explain: "The fixed advice formula is If I were you." },
    ],
  },
  {
    id: "nuance-modals",
    label: "Modal Nuance",
    emoji: "🎚️",
    questions: [
      { q: "You ____ have told me — I was worried!", options: ["should", "must", "can", "would"], correct: 0,
        explain: "Should have + participle criticises something that did not happen." },
      { q: "You ____ have carried that alone; I'd have helped.", options: ["mustn't", "needn't", "can't", "shouldn't"], correct: 1,
        explain: "Needn't have = you did it, but it was unnecessary." },
      { q: "You ____ touch that — it's dangerous.", options: ["needn't", "mustn't", "don't have to", "couldn't"], correct: 1,
        explain: "Mustn't = prohibition. Don't have to = no obligation. Very different." },
      { q: "We ____ pay — entry is free.", options: ["mustn't", "don't have to", "shouldn't", "can't"], correct: 1,
        explain: "No obligation exists, so don't have to." },
      { q: "He ____ be stuck in traffic, I suppose.", options: ["must", "may", "can", "shall"], correct: 1,
        explain: '"I suppose" signals a guess → may.' },
      { q: "____ you mind holding this?", options: ["Should", "Would", "Must", "Shall"], correct: 1,
        explain: "Would you mind is the polite request form." },
      { q: "I ____ swim when I was five.", options: ["could", "was able to", "managed to", "can"], correct: 0,
        explain: "Could describes a general past ability; was able to suits one specific occasion." },
      { q: "The fire was big, but they ____ escape.", options: ["could", "were able to", "can", "would"], correct: 1,
        explain: "One successful action in a difficult moment takes were able to, not could." },
    ],
  },
  {
    id: "word-formation",
    label: "Word Formation",
    emoji: "🧩",
    questions: [
      { q: "She showed great ____. (strong)", options: ["strongness", "strength", "strengthen", "strongly"], correct: 1,
        explain: "The noun from strong is strength — an irregular form." },
      { q: "The film was very ____. (success)", options: ["successful", "successfully", "succeed", "success"], correct: 0,
        explain: "An adjective is needed after was: successful." },
      { q: "He behaved ____. (responsible)", options: ["responsible", "responsibly", "responsibility", "response"], correct: 1,
        explain: "Modifying a verb requires the adverb responsibly." },
      { q: "There's been a big ____ in prices. (increase)", options: ["increasing", "increased", "increase", "increasingly"], correct: 2,
        explain: 'After "a big" a noun is needed: an increase.' },
      { q: "It's an ____ decision. (economy)", options: ["economic", "economical", "economically", "economist"], correct: 0,
        explain: "Economic relates to the economy; economical means money-saving." },
      { q: "This kettle is very ____. (economy)", options: ["economic", "economical", "economy", "economist"], correct: 1,
        explain: "A device that saves money or energy is economical." },
      { q: "Her ____ surprised everyone. (decide)", options: ["decision", "decisive", "decisively", "deciding"], correct: 0,
        explain: "The noun form is decision." },
      { q: "The instructions were ____. (use)", options: ["useful", "useless", "usefully", "using"], correct: 0,
        explain: "An adjective after were; useful is the positive form the sentence implies." },
    ],
  },
  {
    id: "advanced-connectors",
    label: "Advanced Connectors",
    emoji: "🧵",
    questions: [
      { q: "The plan was risky. ____, we approved it.", options: ["Nevertheless", "Moreover", "Therefore", "Likewise"], correct: 0,
        explain: "Nevertheless signals contrast despite the previous fact." },
      { q: "The costs rose. ____, profits fell.", options: ["Nevertheless", "Consequently", "However", "Otherwise"], correct: 1,
        explain: "Consequently introduces a result." },
      { q: "He's talented. ____, he works hard.", options: ["Furthermore", "However", "Otherwise", "Instead"], correct: 0,
        explain: "Furthermore adds a further supporting point." },
      { q: "Hurry up; ____ we'll miss the train.", options: ["therefore", "otherwise", "moreover", "however"], correct: 1,
        explain: "Otherwise = if you do not, this bad thing follows." },
      { q: "____ the report, sales are improving.", options: ["According to", "According with", "Accordingly", "As per to"], correct: 0,
        explain: "According to is the fixed form for citing a source." },
      { q: "She didn't call. ____, she sent a text.", options: ["Instead", "Therefore", "Moreover", "Thus"], correct: 0,
        explain: "Instead marks a replacement action." },
      { q: "____ as the results are, we need more data.", options: ["Encouraging", "Encouraged", "Encouragingly", "Encourage"], correct: 0,
        explain: "Adjective + as + subject + be is a concessive structure." },
      { q: "The design is elegant; ____, it's cheap to build.", options: ["what's more", "whereas", "otherwise", "in case"], correct: 0,
        explain: "What's more adds an extra positive point." },
    ],
  },
  {
    id: "idioms-work",
    label: "Idioms at Work",
    emoji: "💼",
    questions: [
      { q: "Let's ____ the ball rolling.", options: ["make", "get", "take", "put"], correct: 1,
        explain: "Get the ball rolling = start something." },
      { q: "We need to think outside the ____.", options: ["box", "square", "circle", "line"], correct: 0,
        explain: "Think outside the box = think creatively." },
      { q: "That project is on the back ____.", options: ["burner", "shelf", "seat", "line"], correct: 0,
        explain: "On the back burner = postponed, low priority." },
      { q: "Let's touch ____ next week.", options: ["base", "ground", "point", "up"], correct: 0,
        explain: "Touch base = make brief contact." },
      { q: "She really dropped the ____ on that one.", options: ["ball", "stone", "case", "hat"], correct: 0,
        explain: "Drop the ball = fail to handle a responsibility." },
      { q: "We're ____ the same page.", options: ["in", "on", "at", "over"], correct: 1,
        explain: "On the same page = in agreement." },
      { q: "It's a steep learning ____.", options: ["curve", "line", "hill", "road"], correct: 0,
        explain: "A steep learning curve = a lot to learn quickly." },
      { q: "Let's call it a ____.", options: ["day", "night", "time", "end"], correct: 0,
        explain: "Call it a day = stop working for now." },
    ],
  },
];
