// Third batch of Advanced and Expert grammar banks.
//
// Why a third file: the grammar tiers had far less content than the vocabulary
// ones — a child at Advanced saw 4 lessons where a Beginner saw 17, so they
// earned a quarter of the rewards for the same effort. Four exercise types per
// question (js/grammar-client.js) closed most of that gap; these themes close
// the rest, bringing Advanced and Expert to the same 17 lessons as Beginner.
//
// Same shape as the other banks: { q, options[4], correct, explain }.
// `q` must contain "____" — three of the four exercise types fill that gap.

export const ADVANCED_EXTRA2 = [
  {
    id: "mixed-conditionals",
    label: "Condiționale mixte",
    emoji: "🔀",
    questions: [
      { q: "If I ____ harder last year, I would have a better job now.", options: ["studied", "had studied", "would study", "study"], correct: 1,
        explain: "Past cause, present result: If + past perfect, would + base verb." },
      { q: "If she weren't so shy, she ____ asked him yesterday.", options: ["would have", "would", "will have", "had"], correct: 0,
        explain: "A permanent trait explaining a past event: If + past simple, would have + participle." },
      { q: "If we had left earlier, we ____ there by now.", options: ["would be", "would have been", "will be", "were"], correct: 0,
        explain: '"By now" points at the present, so the result half is would + base verb.' },
      { q: "I wouldn't be so tired if I ____ to bed earlier last night.", options: ["went", "had gone", "would go", "go"], correct: 1,
        explain: "Present result, past cause — the if-half takes past perfect." },
      { q: "If he ____ a careful driver, he wouldn't have crashed.", options: ["was", "were", "had been", "would be"], correct: 1,
        explain: "A general characteristic uses the past simple (were), even about a past event." },
      { q: "She would have passed if she ____ better at maths.", options: ["was", "were", "had been", "is"], correct: 1,
        explain: "An ongoing ability, so past simple were — not the past perfect." },
      { q: "If I hadn't missed that train, I ____ standing here now.", options: ["wouldn't be", "wouldn't have been", "won't be", "am not"], correct: 0,
        explain: '"Now" makes the result present: wouldn\'t be.' },
      { q: "If they spoke English, the meeting ____ much easier yesterday.", options: ["would be", "would have been", "will be", "had been"], correct: 1,
        explain: "Permanent situation, past result: would have been." },
    ],
  },
  {
    id: "countable-uncountable",
    label: "Numărabile și nenumărabile",
    emoji: "🧮",
    questions: [
      { q: "Could you give me some ____ about the course?", options: ["informations", "information", "an information", "informative"], correct: 1,
        explain: "Information is uncountable — no plural, no a/an." },
      { q: "She gave me a useful piece of ____.", options: ["advices", "advice", "an advice", "advising"], correct: 1,
        explain: 'Advice is uncountable; you count it with "a piece of".' },
      { q: "How ____ luggage are you taking?", options: ["many", "much", "few", "several"], correct: 1,
        explain: "Luggage is uncountable, so much rather than many." },
      { q: "There ____ a lot of furniture in this room.", options: ["are", "is", "were", "have"], correct: 1,
        explain: "Furniture is uncountable and takes a singular verb." },
      { q: "I need to buy a new pair of ____.", options: ["trouser", "trousers", "trouseres", "the trouser"], correct: 1,
        explain: "Trousers is always plural; a single item is a pair of trousers." },
      { q: "He made good ____ on the project.", options: ["progresses", "progress", "a progress", "progressing"], correct: 1,
        explain: "Progress is uncountable." },
      { q: "The ____ are on the table — help yourself.", options: ["fruit", "fruits", "fruit's", "a fruit"], correct: 0,
        explain: "Fruit is normally uncountable; fruits means different varieties." },
      { q: "We had some interesting ____ during the trip.", options: ["experience", "experiences", "an experience", "experiencing"], correct: 1,
        explain: "Experience is countable when it means individual events." },
    ],
  },
  {
    id: "causative",
    label: "Have / get something done",
    emoji: "🛠️",
    questions: [
      { q: "I need to have my hair ____.", options: ["cut", "to cut", "cutting", "cuts"], correct: 0,
        explain: "have + object + past participle: someone else does it for you." },
      { q: "We're getting the kitchen ____ next month.", options: ["paint", "painted", "painting", "to paint"], correct: 1,
        explain: "get + object + past participle works the same way as have." },
      { q: "She had her passport ____ at the airport.", options: ["steal", "stole", "stolen", "stealing"], correct: 2,
        explain: "The same structure also reports something unpleasant happening to you." },
      { q: "I'll have the report ____ by Friday.", options: ["finish", "finished", "finishing", "to finish"], correct: 1,
        explain: "Past participle after the object — the report receives the action." },
      { q: "They had the mechanic ____ the brakes.", options: ["checked", "check", "checking", "to check"], correct: 1,
        explain: "When you NAME the person, the base verb follows: have someone do something." },
      { q: "He got his brother ____ him with the homework.", options: ["help", "helped", "to help", "helping"], correct: 2,
        explain: "get + person + to-infinitive, unlike have + person + base verb." },
      { q: "Where do you get your shoes ____?", options: ["repair", "repaired", "repairing", "to repair"], correct: 1,
        explain: "The shoes are repaired by someone else — past participle." },
      { q: "I must have this tooth ____ out.", options: ["take", "taken", "taking", "took"], correct: 1,
        explain: "After a modal: have + object + past participle." },
    ],
  },
  {
    id: "time-clauses",
    label: "Propoziții de timp",
    emoji: "⏰",
    questions: [
      { q: "I'll call you when I ____ home.", options: ["will get", "get", "am getting", "would get"], correct: 1,
        explain: "After when/as soon as/until, the present simple carries future meaning." },
      { q: "Wait here until she ____ back.", options: ["will come", "comes", "is coming", "came"], correct: 1,
        explain: "No will after until — the present simple does the work." },
      { q: "As soon as the film ____, we'll go for pizza.", options: ["will end", "ends", "is ending", "ended"], correct: 1,
        explain: "As soon as behaves like when: present simple for the future." },
      { q: "Before you ____, please lock the door.", options: ["will leave", "leave", "are leaving", "left"], correct: 1,
        explain: "Time clause with before takes the present simple." },
      { q: "By the time we arrived, the show ____.", options: ["started", "had started", "has started", "was starting"], correct: 1,
        explain: "By the time + past → the earlier action takes the past perfect." },
      { q: "I'll have finished by the time you ____.", options: ["will arrive", "arrive", "arrived", "are arriving"], correct: 1,
        explain: "Again no will inside the time clause." },
      { q: "After she ____ the email, she felt much calmer.", options: ["sends", "had sent", "will send", "is sending"], correct: 1,
        explain: "The first of two past actions takes the past perfect." },
      { q: "We'll wait while you ____ ready.", options: ["will get", "get", "got", "are getting ready to"], correct: 1,
        explain: "While also blocks will in a future time clause." },
    ],
  },
  {
    id: "verb-patterns",
    label: "Make, let, allow",
    emoji: "🎛️",
    questions: [
      { q: "My parents don't let me ____ out late.", options: ["to stay", "stay", "staying", "stayed"], correct: 1,
        explain: "let + object + BASE verb, with no to." },
      { q: "The teacher made us ____ the exercise again.", options: ["to do", "do", "doing", "done"], correct: 1,
        explain: "make + object + base verb in the active voice." },
      { q: "We were made ____ the room before leaving.", options: ["tidy", "to tidy", "tidying", "tidied"], correct: 1,
        explain: 'In the PASSIVE, make takes "to": we were made to tidy.' },
      { q: "They don't allow people ____ here.", options: ["smoke", "to smoke", "smoking", "smoked"], correct: 1,
        explain: "allow + object + to-infinitive." },
      { q: "Smoking isn't ____ in this building.", options: ["let", "allowed", "made", "permitted to"], correct: 1,
        explain: "Let has no passive; allowed/permitted covers it." },
      { q: "She helped me ____ my luggage.", options: ["carrying", "carry", "carried", "to carrying"], correct: 1,
        explain: "Help takes either the base verb or to + verb; carry is correct here." },
      { q: "I heard someone ____ my name.", options: ["to call", "call", "called", "calls"], correct: 1,
        explain: "Verbs of perception take the base verb for a completed action." },
      { q: "I saw her ____ across the street.", options: ["to run", "running", "ran", "runs"], correct: 1,
        explain: "The -ing form shows the action in progress as you watched." },
    ],
  },
  {
    id: "future-perfect",
    label: "Viitor perfect și continuu",
    emoji: "🔮",
    questions: [
      { q: "By next June I ____ here for ten years.", options: ["will work", "will have worked", "am working", "will be working"], correct: 1,
        explain: "Future perfect: finished by a point in the future." },
      { q: "This time tomorrow we ____ on the beach.", options: ["will lie", "will be lying", "will have lain", "lie"], correct: 1,
        explain: "Future continuous: in progress at that future moment." },
      { q: "Don't call at eight — I ____ dinner.", options: ["will have", "will be having", "have", "will have had"], correct: 1,
        explain: "An activity in progress at a stated time → future continuous." },
      { q: "By the time you read this, I ____.", options: ["will leave", "will have left", "am leaving", "leave"], correct: 1,
        explain: "Completed before another future event → future perfect." },
      { q: "She ____ for six hours by the time she lands.", options: ["will fly", "will have been flying", "flies", "is flying"], correct: 1,
        explain: "Duration up to a future point → future perfect continuous." },
      { q: "____ you be using the car tonight?", options: ["Will", "Would", "Do", "Are"], correct: 0,
        explain: "Future continuous is also a polite way to ask about plans." },
      { q: "In ten years' time robots ____ most of this work.", options: ["will do", "will have done", "will be doing", "do"], correct: 2,
        explain: "An ongoing state of affairs at a future time → future continuous." },
      { q: "I hope I ____ my driving test by the summer.", options: ["will pass", "will have passed", "pass", "am passing"], correct: 1,
        explain: '"By the summer" sets a deadline → future perfect.' },
    ],
  },
  {
    id: "participle-clauses",
    label: "Propoziții participiale",
    emoji: "✂️",
    questions: [
      { q: "____ the door, she noticed the light was on.", options: ["Open", "Opening", "Opened", "To open"], correct: 1,
        explain: "-ing replaces an active clause: When she opened the door…" },
      { q: "____ in 1890, the bridge still stands.", options: ["Building", "Built", "To build", "Build"], correct: 1,
        explain: "The past participle carries passive meaning: Although it was built…" },
      { q: "____ what to say, he stayed silent.", options: ["Not knowing", "Not known", "Don't know", "Not to know"], correct: 0,
        explain: "The negative goes before the -ing form." },
      { q: "____ the film, we went for a walk.", options: ["Having watched", "Watched", "Watching", "To watch"], correct: 0,
        explain: "Having + participle marks the earlier of two actions." },
      { q: "The man ____ over there is my uncle.", options: ["stand", "standing", "stood", "to stand"], correct: 1,
        explain: "-ing shortens a relative clause: the man who is standing." },
      { q: "The results, ____ last week, were disappointing.", options: ["publishing", "published", "publish", "to publish"], correct: 1,
        explain: "Passive meaning — the results were published." },
      { q: "____ by the noise, the baby started to cry.", options: ["Waking", "Woken", "Wake", "To wake"], correct: 1,
        explain: "The baby received the action, so the past participle is right." },
      { q: "____ harder, she would have finished on time.", options: ["Working", "Having worked", "Worked", "To work"], correct: 1,
        explain: "Having worked expresses the completed cause." },
    ],
  },
  {
    id: "agreement",
    label: "Acordul subiect–verb",
    emoji: "🔗",
    questions: [
      { q: "The news ____ better today.", options: ["are", "is", "were", "have"], correct: 1,
        explain: "News looks plural but is uncountable and singular." },
      { q: "Everybody ____ the answer.", options: ["know", "knows", "are knowing", "have known"], correct: 1,
        explain: "Everybody, somebody and nobody all take a singular verb." },
      { q: "The police ____ already arrived.", options: ["has", "have", "is", "was"], correct: 1,
        explain: "Police is always plural in English." },
      { q: "Neither of the answers ____ correct.", options: ["are", "is", "were", "have"], correct: 1,
        explain: "Neither of + plural noun still takes a singular verb." },
      { q: "Mathematics ____ my favourite subject.", options: ["are", "is", "were", "have"], correct: 1,
        explain: "Subjects ending in -ics are singular." },
      { q: "The team ____ playing brilliantly this season.", options: ["is", "are", "has", "was"], correct: 1,
        explain: "A group acting as individuals takes a plural verb in British usage." },
      { q: "There ____ a lot of people outside.", options: ["is", "are", "was", "has"], correct: 1,
        explain: "The real subject is people, which is plural." },
      { q: "Ten kilometres ____ a long way to walk.", options: ["are", "is", "were", "have"], correct: 1,
        explain: "A measured amount is treated as one single quantity." },
    ],
  },
  {
    id: "indirect-questions",
    label: "Întrebări indirecte",
    emoji: "🙋",
    questions: [
      { q: "Could you tell me where ____?", options: ["is the station", "the station is", "is station", "does the station"], correct: 1,
        explain: "Indirect questions use statement word order — no inversion." },
      { q: "I wonder what time ____.", options: ["does it start", "it starts", "is it starting", "start it"], correct: 1,
        explain: "No auxiliary do in an indirect question." },
      { q: "Do you know if ____ open?", options: ["is the shop", "the shop is", "does the shop", "the shop does"], correct: 1,
        explain: "If introduces the clause; word order stays as a statement." },
      { q: "Can you tell me why ____ late?", options: ["was he", "he was", "did he be", "he did be"], correct: 1,
        explain: "Why + subject + verb, without inversion." },
      { q: "I would like to know how much ____.", options: ["does it cost", "it costs", "costs it", "is it cost"], correct: 1,
        explain: "The indirect form drops does and keeps the -s on the verb." },
      { q: "She asked me where ____ from.", options: ["was I", "I was", "did I be", "I did"], correct: 1,
        explain: "Reported questions follow the same statement order." },
      { q: "Have you any idea when ____?", options: ["will they arrive", "they will arrive", "do they arrive", "arrive they"], correct: 1,
        explain: "After when, the subject comes before the verb." },
      { q: "I am not sure whether ____ coming.", options: ["is she", "she is", "does she", "she does be"], correct: 1,
        explain: "Whether behaves exactly like if here." },
    ],
  },
  {
    id: "obligation-permission",
    label: "Obligație și permisiune",
    emoji: "🚦",
    questions: [
      { q: "You ____ wear a helmet — it is the law.", options: ["should", "must", "could", "might"], correct: 1,
        explain: "Must expresses strong obligation, often a rule." },
      { q: "I ____ work on Saturdays, but I choose to.", options: ["mustn't", "don't have to", "can't", "shouldn't"], correct: 1,
        explain: "Don't have to = no obligation, which is not the same as prohibition." },
      { q: "Students ____ use phones during the exam.", options: ["don't have to", "mustn't", "needn't", "could not"], correct: 1,
        explain: "Mustn't = it is forbidden." },
      { q: "____ I borrow your pen?", options: ["Must", "May", "Should", "Ought"], correct: 1,
        explain: "May is the polite way to ask permission." },
      { q: "We ____ to be there by six.", options: ["must", "have", "should to", "can"], correct: 1,
        explain: "Have TO takes the to; must never does." },
      { q: "You ____ have told me sooner.", options: ["must", "should", "can", "may"], correct: 1,
        explain: "Should have + participle criticises a past omission." },
      { q: "He ____ swim when he was four.", options: ["can", "could", "may", "must"], correct: 1,
        explain: "Could describes past ability." },
      { q: "You ____ bring a gift — it is not expected.", options: ["mustn't", "needn't", "can't", "shouldn't"], correct: 1,
        explain: "Needn't = it is unnecessary." },
    ],
  },
  {
    id: "double-comparatives",
    label: "Comparative duble",
    emoji: "📈",
    questions: [
      { q: "The more you practise, ____ you get.", options: ["the better", "better", "the best", "more better"], correct: 0,
        explain: "The + comparative … the + comparative is the fixed pattern." },
      { q: "The harder it rained, ____ we drove.", options: ["slower", "the slower", "the slowest", "more slow"], correct: 1,
        explain: "Both halves need the." },
      { q: "It is getting ____.", options: ["more and more cold", "colder and colder", "the colder", "cold and cold"], correct: 1,
        explain: "Short adjectives double with -er and -er." },
      { q: "The film got ____ interesting.", options: ["more and more", "interestinger", "the more", "much more much"], correct: 0,
        explain: "Long adjectives use more and more." },
      { q: "The sooner we leave, ____.", options: ["the better", "better", "best", "more good"], correct: 0,
        explain: "The better completes the fixed pair." },
      { q: "He is ____ than his brother.", options: ["more taller", "taller", "the taller most", "tallest"], correct: 1,
        explain: "Never combine more with an -er ending." },
      { q: "This is by ____ the best option.", options: ["far", "much", "many", "long"], correct: 0,
        explain: "By far strengthens a superlative." },
      { q: "She sings ____ better than me.", options: ["very", "much", "many", "so"], correct: 1,
        explain: "Much (or far) intensifies a comparative; very cannot." },
    ],
  },
  {
    id: "prepositional-verbs",
    label: "Verbe cu prepoziție",
    emoji: "🔌",
    questions: [
      { q: "I am looking forward ____ your reply.", options: ["for", "to", "at", "on"], correct: 1,
        explain: "Look forward TO — and that to is a preposition." },
      { q: "She insisted ____ paying.", options: ["to", "on", "for", "at"], correct: 1,
        explain: "Insist on is fixed." },
      { q: "They accused him ____ lying.", options: ["for", "of", "with", "about"], correct: 1,
        explain: "Accuse someone OF something." },
      { q: "We are relying ____ you.", options: ["of", "on", "at", "to"], correct: 1,
        explain: "Rely on is fixed." },
      { q: "He apologised ____ his behaviour.", options: ["of", "for", "about", "to"], correct: 1,
        explain: "Apologise FOR the thing, TO the person." },
      { q: "This belongs ____ me.", options: ["of", "to", "for", "with"], correct: 1,
        explain: "Belong to is fixed." },
      { q: "She succeeded ____ passing the exam.", options: ["to", "in", "at", "on"], correct: 1,
        explain: "Succeed IN doing something." },
      { q: "They objected ____ the new rule.", options: ["against", "to", "for", "at"], correct: 1,
        explain: "Object to is fixed." },
    ],
  },
  {
    id: "purpose-result",
    label: "Scop și rezultat",
    emoji: "🎯",
    questions: [
      { q: "He left early ____ avoid the traffic.", options: ["for", "to", "for to", "so"], correct: 1,
        explain: "To + base verb expresses purpose; for + verb is wrong." },
      { q: "She saved money ____ buy a bike.", options: ["for to", "to", "for", "so to"], correct: 1,
        explain: "Purpose takes the to-infinitive." },
      { q: "I took notes ____ I would remember.", options: ["so that", "for that", "in order", "to that"], correct: 0,
        explain: "So that introduces a clause with its own subject." },
      { q: "It was ____ cold that we stayed in.", options: ["such", "so", "too", "very"], correct: 1,
        explain: "So + adjective + that expresses result." },
      { q: "It was ____ a cold day that we stayed in.", options: ["so", "such", "too", "very"], correct: 1,
        explain: "Such + a + adjective + noun." },
      { q: "He studied hard ____ to pass.", options: ["in order", "for", "so", "that"], correct: 0,
        explain: "In order to is the formal purpose phrase." },
      { q: "Take a map ____ you get lost.", options: ["in case", "for case", "in the case", "so case"], correct: 0,
        explain: "In case = as a precaution." },
      { q: "She spoke slowly ____ be understood.", options: ["for", "so as to", "so that to", "in order that"], correct: 1,
        explain: "So as to + base verb is the formal purpose form." },
    ],
  },
  {
    id: "determiners",
    label: "Determinanți",
    emoji: "🔢",
    questions: [
      { q: "____ of my parents came.", options: ["Both", "Every", "Each one", "All the two"], correct: 0,
        explain: "Both refers to exactly two." },
      { q: "____ student received a book.", options: ["Every", "All", "Both", "Most of"], correct: 0,
        explain: "Every + singular noun." },
      { q: "____ students passed.", options: ["Every", "All", "Each of", "Both the"], correct: 1,
        explain: "All + plural noun." },
      { q: "____ of the boys has his own room.", options: ["All", "Each", "Both the", "Every"], correct: 1,
        explain: "Each of + plural noun + singular verb." },
      { q: "There were shops on ____ side.", options: ["both", "either", "all", "every one"], correct: 1,
        explain: "Either + singular noun = one and the other." },
      { q: "I do not like ____ of them.", options: ["neither", "either", "both not", "every"], correct: 1,
        explain: "After a negative, use either — not neither." },
      { q: "____ the students were late.", options: ["Most of", "Most", "The most of", "Almost"], correct: 0,
        explain: "Most OF before the." },
      { q: "She has ____ friends here.", options: ["a little", "few", "much", "less"], correct: 1,
        explain: "Few + countable plural." },
    ],
  },
  {
    id: "spelling-rules",
    label: "Reguli de ortografie",
    emoji: "✒️",
    questions: [
      { q: "study → he ____", options: ["studys", "studies", "studyes", "studis"], correct: 1,
        explain: "Consonant + y becomes -ies." },
      { q: "play → he ____", options: ["plaies", "plays", "playes", "plais"], correct: 1,
        explain: "Vowel + y just adds -s." },
      { q: "stop → ____", options: ["stoping", "stopping", "stopeing", "stoppping"], correct: 1,
        explain: "One vowel + one consonant doubles the consonant." },
      { q: "make → ____", options: ["makeing", "making", "makking", "makin"], correct: 1,
        explain: "Silent e is dropped before -ing." },
      { q: "big → ____", options: ["biger", "bigger", "bigest", "biggger"], correct: 1,
        explain: "The final consonant doubles before -er." },
      { q: "happy → ____", options: ["happyer", "happier", "happyier", "more happy"], correct: 1,
        explain: "y becomes i before -er." },
      { q: "travel → ____ (British)", options: ["traveling", "travelling", "travelingg", "travling"], correct: 1,
        explain: "British English doubles the l; American spells it traveling." },
      { q: "lie → ____", options: ["lieing", "lying", "lyeing", "liying"], correct: 1,
        explain: "-ie becomes -y before -ing." },
    ],
  },
];

export const EXPERT_EXTRA2 = [
  {
    id: "cleft-sentences",
    label: "Propoziții scindate",
    emoji: "🔦",
    questions: [
      { q: "____ I need is a holiday.", options: ["That", "What", "Which", "It"], correct: 1,
        explain: "What-clefts front the important part: What I need is…" },
      { q: "____ was Ana who solved it, not me.", options: ["That", "It", "She", "There"], correct: 1,
        explain: "It-clefts single out one element: It was Ana who…" },
      { q: "____ he said annoyed everyone.", options: ["What", "That", "Which", "It"], correct: 0,
        explain: "What = the thing that, acting as the subject." },
      { q: "All ____ want is a quiet evening.", options: ["what I", "that I", "I", "which I"], correct: 2,
        explain: "After All, no relative word is needed: All I want is…" },
      { q: "It was in Cluj ____ we first met.", options: ["which", "that", "what", "when"], correct: 1,
        explain: "That follows the fronted element in an it-cleft." },
      { q: "____ happened next surprised us all.", options: ["That", "It", "What", "Which"], correct: 2,
        explain: "What introduces the noun clause acting as subject." },
      { q: "The reason ____ I called is simple.", options: ["what", "why", "which", "that"], correct: 1,
        explain: "The reason why (or the reason that) is the fixed pairing." },
      { q: "____ they did was completely unfair.", options: ["That", "What", "Which", "It"], correct: 1,
        explain: "Again a what-cleft fronting the action for emphasis." },
    ],
  },
  {
    id: "hedging",
    label: "Nuanțare și prudență",
    emoji: "🌫️",
    questions: [
      { q: "The results ____ that costs are rising.", options: ["prove", "suggest", "show definitely", "confirm totally"], correct: 1,
        explain: "Suggest hedges a claim; prove overstates it." },
      { q: "This ____ be the main cause.", options: ["is", "may well", "definitely is", "must totally"], correct: 1,
        explain: "May well signals a likely but unproven conclusion." },
      { q: "Prices are ____ higher than last year.", options: ["absolutely", "somewhat", "totally", "completely"], correct: 1,
        explain: "Somewhat softens a comparison." },
      { q: "It ____ that the policy has failed.", options: ["appears", "is obvious", "proves", "is certain"], correct: 0,
        explain: "It appears that… is the cautious academic form." },
      { q: "There is a ____ possibility of delay.", options: ["total", "slight", "definite total", "complete"], correct: 1,
        explain: "Slight scales the claim down honestly." },
      { q: "The data ____ support this view.", options: ["totally", "tend to", "absolutely", "certainly all"], correct: 1,
        explain: "Tend to marks a general trend rather than a rule." },
      { q: "This is ____ the best available option.", options: ["arguably", "obviously totally", "undeniably all", "surely completely"], correct: 0,
        explain: "Arguably admits that others might disagree." },
      { q: "Further research ____ be needed.", options: ["will definitely", "would", "totally will", "must always"], correct: 1,
        explain: "Would softens a recommendation into a suggestion." },
    ],
  },
  {
    id: "discourse-markers",
    label: "Marcatori de discurs",
    emoji: "🧭",
    questions: [
      { q: "____, let's look at the numbers.", options: ["Firstly", "At first", "First of all time", "In the first"], correct: 0,
        explain: "Firstly (or First of all) opens a sequence; at first means initially." },
      { q: "The plan is risky. ____, it may work.", options: ["Even so", "Even though", "Despite", "Although"], correct: 0,
        explain: "Even so links two sentences; even though needs one clause." },
      { q: "____, the delay was our fault.", options: ["To be honest", "For be honest", "Honest speaking", "In honest"], correct: 0,
        explain: "To be honest is the fixed discourse marker." },
      { q: "He's late again. ____, he always is.", options: ["Mind you", "Mind that", "Mind of you", "Never mind you"], correct: 0,
        explain: "Mind you adds a qualifying afterthought." },
      { q: "____, how did the interview go?", options: ["By the way", "In the way", "On the way", "For the way"], correct: 0,
        explain: "By the way introduces a change of topic." },
      { q: "____, we should have booked earlier.", options: ["In hindsight", "In behind sight", "At hindsight", "On hindsight"], correct: 0,
        explain: "In hindsight = looking back afterwards." },
      { q: "The trip was long. ____, it was worth it.", options: ["That said", "That saying", "This said that", "Said that"], correct: 0,
        explain: "That said concedes the previous point before contrasting." },
      { q: "____, nothing has changed since.", options: ["As far as I know", "So far I know", "As far I know", "For all I know that"], correct: 0,
        explain: "As far as I know is the fixed hedging phrase." },
    ],
  },
  {
    id: "binomials",
    label: "Perechi fixe",
    emoji: "⚖️",
    questions: [
      { q: "Let's weigh the pros and ____.", options: ["contras", "cons", "againsts", "opposites"], correct: 1,
        explain: "Pros and cons is fixed and never reversed." },
      { q: "The room was neat and ____.", options: ["tidy", "clean", "ordered", "arranged"], correct: 0,
        explain: "Neat and tidy is a set pair." },
      { q: "Sooner or ____ he'll find out.", options: ["later", "after", "then", "late"], correct: 0,
        explain: "Sooner or later is fixed." },
      { q: "We searched high and ____.", options: ["down", "low", "deep", "wide"], correct: 1,
        explain: "High and low means everywhere." },
      { q: "It's a matter of trial and ____.", options: ["mistake", "error", "fault", "failure"], correct: 1,
        explain: "Trial and error is the set phrase." },
      { q: "By and ____, the plan worked.", options: ["large", "big", "wide", "far"], correct: 0,
        explain: "By and large = generally speaking." },
      { q: "Sick and ____ of waiting.", options: ["bored", "tired", "angry", "done"], correct: 1,
        explain: "Sick and tired of is fixed." },
      { q: "They arrived safe and ____.", options: ["sure", "sound", "well", "healthy"], correct: 1,
        explain: "Safe and sound is the idiom." },
    ],
  },
  {
    id: "delexical-verbs",
    label: "Verbe golite de sens",
    emoji: "🫗",
    questions: [
      { q: "Let's ____ a look at the figures.", options: ["do", "make", "have", "give"], correct: 2,
        explain: "Have a look is the natural pairing." },
      { q: "She ____ a deep breath and started.", options: ["did", "made", "took", "gave"], correct: 2,
        explain: "Take a breath is fixed." },
      { q: "I'll ____ a try.", options: ["do", "give it", "make", "take"], correct: 1,
        explain: "Give it a try is the idiomatic form." },
      { q: "We ____ a decision this morning.", options: ["did", "made", "took", "had"], correct: 1,
        explain: "Make a decision — never do a decision." },
      { q: "He ____ a shower before work.", options: ["makes", "does", "has", "gives"], correct: 2,
        explain: "Have a shower (British) or take a shower (American)." },
      { q: "Can you ____ me a hand?", options: ["do", "make", "give", "have"], correct: 2,
        explain: "Give someone a hand = help them." },
      { q: "They ____ a party last weekend.", options: ["made", "had", "did", "took"], correct: 1,
        explain: "Have a party is the standard collocation." },
      { q: "I need to ____ a phone call.", options: ["do", "make", "have", "take"], correct: 1,
        explain: "Make a phone call is fixed." },
    ],
  },
  {
    id: "ellipsis",
    label: "Elipsă și substituție",
    emoji: "➖",
    questions: [
      { q: '"Are you coming?" "I hope ____."', options: ["it", "so", "that", "this"], correct: 1,
        explain: "So substitutes for a whole clause after hope, think, believe." },
      { q: '"Will it rain?" "I hope ____."', options: ["not", "no", "don't", "not so"], correct: 0,
        explain: "I hope not is the negative form of I hope so." },
      { q: "She can swim and so ____ I.", options: ["do", "can", "am", "have"], correct: 1,
        explain: "The substitute repeats the same auxiliary: so can I." },
      { q: "He doesn't like it and neither ____ she.", options: ["does", "do", "is", "has"], correct: 0,
        explain: "Neither + auxiliary + subject, matching the original verb." },
      { q: "I'd love to come but I can't ____.", options: ["make", "do it", "—", "so"], correct: 2,
        explain: "After can't, the verb is simply left out — nothing is needed." },
      { q: "\"Who broke it?\" \"Not ____.\"", options: ["I", "me", "mine", "myself"], correct: 1,
        explain: "In short answers English uses the object form: Not me." },
      { q: "I have a red one and she has a blue ____.", options: ["one", "it", "that", "some"], correct: 0,
        explain: "One substitutes for a countable noun already mentioned." },
      { q: "They said they'd help and they ____.", options: ["do", "did", "have", "were"], correct: 1,
        explain: "The auxiliary alone stands in for the whole verb phrase." },
    ],
  },
  {
    id: "idioms-nature",
    label: "Idiomuri din natură",
    emoji: "🌦️",
    questions: [
      { q: "It's raining cats and ____.", options: ["dogs", "mice", "birds", "frogs"], correct: 0,
        explain: "Raining cats and dogs = raining very heavily." },
      { q: "He's under the ____ today.", options: ["cloud", "weather", "rain", "sky"], correct: 1,
        explain: "Under the weather = feeling unwell." },
      { q: "That's just the tip of the ____.", options: ["mountain", "iceberg", "hill", "stone"], correct: 1,
        explain: "The tip of the iceberg = a small visible part of a big problem." },
      { q: "Every cloud has a silver ____.", options: ["edge", "lining", "side", "line"], correct: 1,
        explain: "There is something good in every bad situation." },
      { q: "Let's take a rain ____ on that.", options: ["check", "test", "date", "call"], correct: 0,
        explain: "Take a rain check = postpone politely." },
      { q: "She was over the ____ about the news.", options: ["sun", "moon", "sky", "stars"], correct: 1,
        explain: "Over the moon = delighted." },
      { q: "He's barking up the wrong ____.", options: ["tree", "wall", "road", "path"], correct: 0,
        explain: "Pursuing a mistaken idea." },
      { q: "They're out of the ____ now.", options: ["woods", "forest", "trees", "field"], correct: 0,
        explain: "Out of the woods = past the dangerous part." },
    ],
  },
  {
    id: "idioms-body",
    label: "Idiomuri cu părți ale corpului",
    emoji: "🖐️",
    questions: [
      { q: "It cost an arm and a ____.", options: ["hand", "leg", "foot", "head"], correct: 1,
        explain: "An arm and a leg = extremely expensive." },
      { q: "Keep an ____ on the time.", options: ["ear", "eye", "arm", "hand"], correct: 1,
        explain: "Keep an eye on = watch carefully." },
      { q: "Let's play it by ____.", options: ["ear", "eye", "hand", "head"], correct: 0,
        explain: "Play it by ear = improvise as you go." },
      { q: "She gave me the cold ____.", options: ["arm", "shoulder", "hand", "back"], correct: 1,
        explain: "The cold shoulder = deliberate unfriendliness." },
      { q: "He's got a good ____ for business.", options: ["head", "hand", "eye", "mind"], correct: 0,
        explain: "A good head for = a natural talent." },
      { q: "That's off the top of my ____.", options: ["mind", "head", "brain", "thought"], correct: 1,
        explain: "Off the top of my head = without checking." },
      { q: "Don't put your ____ in it.", options: ["leg", "foot", "arm", "hand"], correct: 1,
        explain: "Put your foot in it = say something embarrassing." },
      { q: "We see eye to ____ on this.", options: ["eye", "face", "head", "ear"], correct: 0,
        explain: "See eye to eye = agree completely." },
    ],
  },
  {
    id: "academic-verbs",
    label: "Verbe formale",
    emoji: "🎓",
    questions: [
      { q: "The study ____ three main causes.", options: ["found out", "identified", "spotted", "dug up"], correct: 1,
        explain: "Identify is the formal single-word verb." },
      { q: "These figures ____ our earlier findings.", options: ["back up", "corroborate", "prop up", "hold up"], correct: 1,
        explain: "Corroborate is the academic register." },
      { q: "The author ____ that costs will fall.", options: ["reckons", "contends", "guesses", "figures"], correct: 1,
        explain: "Contend = argue a position formally." },
      { q: "We must ____ the impact of the change.", options: ["work out", "evaluate", "sort out", "check out"], correct: 1,
        explain: "Evaluate replaces the phrasal verb in formal writing." },
      { q: "The results ____ a clear pattern.", options: ["show up", "reveal", "turn up", "bring up"], correct: 1,
        explain: "Reveal is the formal choice." },
      { q: "This section ____ the method used.", options: ["talks about", "outlines", "goes into", "gets at"], correct: 1,
        explain: "Outline = describe briefly and formally." },
      { q: "The two theories ____ considerably.", options: ["differ", "are different a lot", "vary up", "split up"], correct: 0,
        explain: "Differ is the concise formal verb." },
      { q: "The paper ____ several limitations.", options: ["owns up to", "acknowledges", "admits to", "fesses up"], correct: 1,
        explain: "Acknowledge is the neutral formal verb." },
    ],
  },
  {
    id: "connotation",
    label: "Conotație",
    emoji: "🎨",
    questions: [
      { q: "Which is the POSITIVE word for someone careful with money?", options: ["stingy", "thrifty", "mean", "tight"], correct: 1,
        explain: "Thrifty is approving; the others are critical." },
      { q: "Which sounds most POSITIVE about a determined person?", options: ["stubborn", "pig-headed", "persistent", "obstinate"], correct: 2,
        explain: "Persistent praises; the rest criticise the same trait." },
      { q: "Which is NEUTRAL for an old person?", options: ["elderly", "ancient", "past it", "decrepit"], correct: 0,
        explain: "Elderly is the neutral term." },
      { q: "Which is the KINDEST word for a thin person?", options: ["skinny", "slender", "scrawny", "bony"], correct: 1,
        explain: "Slender is complimentary." },
      { q: "Which sounds most NEGATIVE about a curious person?", options: ["inquisitive", "interested", "nosy", "keen"], correct: 2,
        explain: "Nosy implies unwelcome prying." },
      { q: "Which is POSITIVE about someone who talks a lot?", options: ["chatty", "gossipy", "mouthy", "loud-mouthed"], correct: 0,
        explain: "Chatty is friendly; the others are critical." },
      { q: "Which is NEUTRAL for a cheap product?", options: ["cheap", "shoddy", "inexpensive", "tacky"], correct: 2,
        explain: "Inexpensive avoids the poor-quality hint that cheap carries." },
      { q: "Which is POSITIVE for someone who takes risks?", options: ["reckless", "bold", "rash", "foolhardy"], correct: 1,
        explain: "Bold admires; the rest disapprove." },
    ],
  },
  {
    id: "sound-alikes",
    label: "Cuvinte care sună la fel",
    emoji: "🔊",
    questions: [
      { q: "The team had a positive ____ on the result.", options: ["affect", "effect", "afect", "efect"], correct: 1,
        explain: "Effect is the noun; affect is the verb." },
      { q: "The weather will ____ our plans.", options: ["effect", "affect", "afect", "effekt"], correct: 1,
        explain: "Affect = to influence, and it is a verb." },
      { q: "They travelled ____ the desert.", options: ["threw", "through", "thorough", "though"], correct: 1,
        explain: "Through = from one side to the other." },
      { q: "You're ____ than you think.", options: ["stronger then", "stronger than", "stronger that", "more strong then"], correct: 1,
        explain: "Than compares; then is about time." },
      { q: "The dog wagged ____ tail.", options: ["it's", "its", "its'", "it is"], correct: 1,
        explain: "Its is possessive; it's means it is." },
      { q: "____ going to be late.", options: ["Their", "There", "They're", "Theyre"], correct: 2,
        explain: "They're = they are." },
      { q: "I'd like to ____ your advice.", options: ["accept", "except", "acept", "exept"], correct: 0,
        explain: "Accept = receive; except = apart from." },
      { q: "Please ____ me to the station.", options: ["led", "lead", "leed", "leaded"], correct: 1,
        explain: "Lead is the present verb; led is its past form." },
    ],
  },
  {
    id: "proverbs",
    label: "Proverbe",
    emoji: "📜",
    questions: [
      { q: "Don't count your chickens before they ____.", options: ["grow", "hatch", "fly", "lay"], correct: 1,
        explain: "Don't assume success before it happens." },
      { q: "The early bird catches the ____.", options: ["worm", "fish", "sun", "day"], correct: 0,
        explain: "Acting early brings the advantage." },
      { q: "Actions speak louder than ____.", options: ["thoughts", "words", "plans", "ideas"], correct: 1,
        explain: "What you do matters more than what you say." },
      { q: "Better late than ____.", options: ["sorry", "never", "nothing", "early"], correct: 1,
        explain: "Arriving late beats not arriving at all." },
      { q: "When in Rome, do as the ____ do.", options: ["Italians", "Romans", "locals", "people"], correct: 1,
        explain: "Adapt to local customs." },
      { q: "Too many cooks spoil the ____.", options: ["soup", "broth", "meal", "dish"], correct: 1,
        explain: "Too many people involved ruins the work." },
      { q: "Don't judge a book by its ____.", options: ["title", "cover", "page", "size"], correct: 1,
        explain: "Appearances mislead." },
      { q: "A picture is worth a thousand ____.", options: ["words", "pages", "stories", "ideas"], correct: 0,
        explain: "An image explains more than a long description." },
    ],
  },
  {
    id: "emphasis-adverbs",
    label: "Adverbe de intensitate",
    emoji: "📢",
    questions: [
      { q: "The film was ____ brilliant.", options: ["very", "absolutely", "much", "too much"], correct: 1,
        explain: "Extreme adjectives take absolutely, not very." },
      { q: "I was ____ tired after the trip.", options: ["absolutely", "utterly exhausted", "very", "completely"], correct: 2,
        explain: "Tired is gradable, so very fits; absolutely needs exhausted." },
      { q: "She was ____ exhausted.", options: ["very", "completely", "a bit very", "much"], correct: 1,
        explain: "Exhausted is already extreme → completely/absolutely." },
      { q: "It's ____ impossible.", options: ["very", "quite a bit", "virtually", "much"], correct: 2,
        explain: "Virtually = almost entirely, and fits an absolute adjective." },
      { q: "I ____ agree with you.", options: ["very", "entirely", "much", "too"], correct: 1,
        explain: "Entirely (or completely) modifies the verb agree." },
      { q: "The room was ____ empty.", options: ["very", "almost", "much", "too much"], correct: 1,
        explain: "Empty is absolute, so almost scales it rather than very." },
      { q: "That's ____ what I meant.", options: ["very", "exactly", "much", "too"], correct: 1,
        explain: "Exactly intensifies the match." },
      { q: "He was ____ furious.", options: ["very", "absolutely", "much", "quite a bit"], correct: 1,
        explain: "Furious is an extreme adjective → absolutely." },
    ],
  },
  {
    id: "nominalisation",
    label: "Substantivizare",
    emoji: "🏛️",
    questions: [
      { q: "Formal noun from \"decide\":", options: ["deciding", "decision", "decisive", "decidement"], correct: 1,
        explain: "Decision is the standard noun form." },
      { q: "Formal noun from \"analyse\":", options: ["analysing", "analysis", "analytic", "analyser"], correct: 1,
        explain: "Analysis is the noun; analyses is its plural." },
      { q: "Formal noun from \"maintain\":", options: ["maintaining", "maintenance", "maintainment", "maintainance"], correct: 1,
        explain: "Maintenance — note the spelling change." },
      { q: "Formal noun from \"argue\":", options: ["arguing", "argument", "arguement", "argumentation only"], correct: 1,
        explain: "Argument drops the e of argue." },
      { q: "Formal noun from \"succeed\":", options: ["succeeding", "success", "successful", "succession only"], correct: 1,
        explain: "Success is the general noun; succession means a sequence." },
      { q: "Formal noun from \"apply\":", options: ["applying", "application", "appliance only", "applicant only"], correct: 1,
        explain: "Application is the act; an applicant is the person." },
      { q: "Formal noun from \"lose\":", options: ["losing", "loss", "lost", "loose"], correct: 1,
        explain: "Loss is the noun; loose is a different word entirely." },
      { q: "Formal noun from \"grow\":", options: ["growing", "growth", "grown", "grewth"], correct: 1,
        explain: "Growth is the noun form." },
    ],
  },
  {
    id: "idioms-money",
    label: "Idiomuri despre bani",
    emoji: "💰",
    questions: [
      { q: "That car cost a small ____.", options: ["fortune", "treasure", "money", "gold"], correct: 0,
        explain: "A small fortune = a great deal of money." },
      { q: "We are trying to make ends ____.", options: ["meet", "join", "touch", "match"], correct: 0,
        explain: "Make ends meet = manage on limited money." },
      { q: "He is rolling ____ money.", options: ["on", "in", "with", "at"], correct: 1,
        explain: "Rolling in money = extremely rich." },
      { q: "That price is a rip-____.", options: ["off", "up", "out", "over"], correct: 0,
        explain: "A rip-off = grossly overpriced." },
      { q: "Let us go ____ on the bill.", options: ["Dutch", "German", "French", "Swiss"], correct: 0,
        explain: "Go Dutch = each person pays their own share." },
      { q: "She is saving for a rainy ____.", options: ["day", "week", "time", "season"], correct: 0,
        explain: "For a rainy day = for a future difficulty." },
      { q: "It is not worth a ____.", options: ["cent", "penny", "coin", "note"], correct: 1,
        explain: "Not worth a penny = worthless." },
      { q: "They are living beyond their ____.", options: ["means", "money", "ways", "limits"], correct: 0,
        explain: "Beyond your means = spending more than you earn." },
    ],
  },
  {
    id: "idioms-time",
    label: "Idiomuri despre timp",
    emoji: "⏳",
    questions: [
      { q: "We finished in the ____ of time.", options: ["nick", "cut", "edge", "point"], correct: 0,
        explain: "In the nick of time = only just in time." },
      { q: "It is late — let us call it a ____.", options: ["day", "night", "time", "end"], correct: 0,
        explain: "Call it a day = stop working for now." },
      { q: "He arrived out of the ____.", options: ["blue", "green", "red", "grey"], correct: 0,
        explain: "Out of the blue = completely unexpectedly." },
      { q: "That happens once in a blue ____.", options: ["sky", "moon", "star", "day"], correct: 1,
        explain: "Once in a blue moon = very rarely." },
      { q: "We are working against the ____.", options: ["hour", "clock", "watch", "minute"], correct: 1,
        explain: "Against the clock = under time pressure." },
      { q: "In the long ____ it will pay off.", options: ["run", "way", "time", "period"], correct: 0,
        explain: "In the long run = eventually." },
      { q: "Time ____ when you are having fun.", options: ["runs", "flies", "jumps", "walks"], correct: 1,
        explain: "Time flies is the fixed saying." },
      { q: "Let us play it by ____ and decide later.", options: ["ear", "eye", "hand", "time"], correct: 0,
        explain: "Play it by ear = decide as you go." },
    ],
  },
  {
    id: "phrasal-separable",
    label: "Verbe cu particulă: poziția",
    emoji: "🔀",
    questions: [
      { q: "The TV is on. Which is correct?", options: ["Turn off it", "Turn it off", "Off turn it", "Turn off of it"], correct: 1,
        explain: "A PRONOUN object must sit between the verb and the particle." },
      { q: "The baby needs care. Which is correct?", options: ["Look after it", "Look it after", "After look it", "Look after of it"], correct: 0,
        explain: "Look after is inseparable — nothing ever splits it." },
      { q: "About smoking. Which is correct?", options: ["Give up it", "Give it up", "Up give it", "Give up of it"], correct: 1,
        explain: "Give up is separable, so the pronoun goes in the middle." },
      { q: "I met her by chance. Which is correct?", options: ["Ran into her", "Ran her into", "Into ran her", "Ran into of her"], correct: 0,
        explain: "Run into (= meet by chance) is inseparable." },
      { q: "About the children. Which is correct?", options: ["Pick up the children", "Pick the children up", "Both are correct", "Neither is correct"], correct: 2,
        explain: "With a NOUN object either position works; only pronouns are fixed." },
      { q: "About your coat. Which is correct?", options: ["Put on it", "Put it on", "On put it", "Put on of it"], correct: 1,
        explain: "Pronoun in the middle again." },
      { q: "About the illness. Which is correct?", options: ["Get over it", "Get it over", "Over get it", "Get of it over"], correct: 0,
        explain: "Get over (= recover from) is inseparable." },
      { q: "About the old boxes. Which is correct?", options: ["Throw away them", "Throw them away", "Away throw them", "Throw away of them"], correct: 1,
        explain: "Throw away is separable, so them goes in the middle." },
    ],
  },
  {
    id: "formal-writing",
    label: "Scriere formală",
    emoji: "✉️",
    questions: [
      { q: "Formal opening to an unknown reader:", options: ["Hi there", "Dear Sir or Madam", "Hello you", "To whoever reads"], correct: 1,
        explain: "Dear Sir or Madam is the standard formal opening." },
      { q: "Formal version of \"I want to complain\":", options: ["I wish to complain", "I wanna complain", "I gotta complain", "I am complaining now"], correct: 0,
        explain: "I wish to is the formal register." },
      { q: "Formal alternative to \"ask for\":", options: ["request", "beg for", "want", "go get"], correct: 0,
        explain: "Request is the neutral formal verb." },
      { q: "Formal alternative to \"sorry about that\":", options: ["We apologise for this", "We are sorry bout it", "Our bad on this", "We regret sorry"], correct: 0,
        explain: "We apologise for is standard." },
      { q: "Formal closing after \"Dear Mr Popescu\":", options: ["Yours sincerely", "Yours faithfully", "Cheers", "Talk soon"], correct: 0,
        explain: "A named recipient takes Yours sincerely; an unnamed one takes faithfully." },
      { q: "Formal alternative to \"tell you about\":", options: ["inform you of", "let you know bout", "fill you in on", "clue you in on"], correct: 0,
        explain: "Inform you of is the formal phrase." },
      { q: "Formal alternative to \"need\":", options: ["require", "gotta have", "want badly", "must get"], correct: 0,
        explain: "Require is the formal verb." },
      { q: "Formal alternative to \"look at\" a document:", options: ["review", "check out", "eyeball", "peek at"], correct: 0,
        explain: "Review is the professional term." },
    ],
  },
  {
    id: "tense-nuance",
    label: "Nuanțe de timp verbal",
    emoji: "🎚️",
    questions: [
      { q: "I ____ in Cluj for ten years — and I still live there.", options: ["lived", "have lived", "live", "was living"], correct: 1,
        explain: "An unfinished period up to now takes the present perfect." },
      { q: "I ____ in Cluj for ten years, then I moved away.", options: ["lived", "have lived", "live", "have been living"], correct: 0,
        explain: "A finished period takes the past simple." },
      { q: "She ____ always losing her keys!", options: ["is", "has", "does", "was"], correct: 0,
        explain: "Present continuous + always expresses irritation at a habit." },
      { q: "The train ____ at 7.15 tomorrow.", options: ["is leaving", "leaves", "will leave", "left"], correct: 1,
        explain: "Timetables take the present simple even about the future." },
      { q: "I ____ him tomorrow — it is all arranged.", options: ["will meet", "am meeting", "meet", "would meet"], correct: 1,
        explain: "A fixed arrangement takes the present continuous." },
      { q: "Look at those clouds — it ____ rain.", options: ["will", "is going to", "shall", "would"], correct: 1,
        explain: "Present evidence points to going to, not will." },
      { q: "That is the phone ringing — I ____ it.", options: ["am getting", "will get", "get", "would get"], correct: 1,
        explain: "A decision made at the moment of speaking takes will." },
      { q: "I ____ tennis since I was six.", options: ["play", "played", "have been playing", "was playing"], correct: 2,
        explain: "Duration continuing up to now takes the present perfect continuous." },
    ],
  },
  {
    id: "quantifier-nuance",
    label: "Nuanțe de cantitate",
    emoji: "🥄",
    questions: [
      { q: "He has ____ friends — he is quite lonely.", options: ["a few", "few", "several", "some"], correct: 1,
        explain: "Few without a is negative: almost none." },
      { q: "He has ____ friends — enough to be happy.", options: ["few", "a few", "little", "a little"], correct: 1,
        explain: "A few is positive: some, and that is fine." },
      { q: "There is ____ hope left — it is nearly over.", options: ["a little", "little", "few", "a few"], correct: 1,
        explain: "Little without a is negative." },
      { q: "There is ____ hope — do not give up yet.", options: ["little", "a little", "few", "a few"], correct: 1,
        explain: "A little is positive: some, though not much." },
      { q: "____ of us knew the answer — nobody did.", options: ["None", "Any", "Not all", "Some"], correct: 0,
        explain: "None of = not one." },
      { q: "____ of us knew — some did, some did not.", options: ["None", "Not all", "No one", "Neither"], correct: 1,
        explain: "Not all leaves room for some." },
      { q: "Hardly ____ came to the party.", options: ["anyone", "no one", "someone", "not anyone"], correct: 0,
        explain: "Hardly is already negative, so it pairs with anyone." },
      { q: "There is scarcely ____ milk left.", options: ["no", "any", "some", "none"], correct: 1,
        explain: "Scarcely is negative and takes any." },
    ],
  },
  {
    id: "commonly-misused",
    label: "Greșeli frecvente",
    emoji: "⚠️",
    questions: [
      { q: "I look forward to ____ from you.", options: ["hear", "hearing", "heard", "be hearing"], correct: 1,
        explain: "The to in look forward to is a preposition, so -ing follows." },
      { q: "He is used to ____ early.", options: ["get up", "getting up", "got up", "gets up"], correct: 1,
        explain: "Be used to + -ing means it is familiar now." },
      { q: "She suggested ____ a break.", options: ["to take", "taking", "take", "us to take"], correct: 1,
        explain: "Suggest takes -ing or that + clause, never to + verb." },
      { q: "I explained ____ the problem.", options: ["him", "to him", "at him", "for him"], correct: 1,
        explain: "Explain something TO someone." },
      { q: "Despite ____ tired, he continued.", options: ["he was", "being", "was", "that he"], correct: 1,
        explain: "Despite takes a noun or -ing form, not a clause." },
      { q: "It depends ____ the weather.", options: ["of", "on", "from", "by"], correct: 1,
        explain: "Depend ON — depend of is a direct-translation error." },
      { q: "I am interested ____ learning more.", options: ["to", "in", "for", "about"], correct: 1,
        explain: "Interested in + -ing." },
      { q: "The information ____ very useful.", options: ["are", "is", "were", "have been"], correct: 1,
        explain: "Information is uncountable and takes a singular verb." },
    ],
  },
];
